version: '3'
services:
  nodeapp: 
    build: 
      context: './calculatorapi'
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    container_name: node-container
    volumes: 
    - ./calculatorapi:/app
    healthcheck:
      test: curl --fail http://localhost:3000/ || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s